---
- name: Disable Firewall (All Profiles)
  community.windows.win_firewall:
    state: disabled
    profiles:
      - Domain
      - Private
      - Public

- name: Enable Remote Desktop (RDP)
  ansible.windows.win_service:
    name: TermService
    start_mode: auto
    state: started

- name: Allow RDP in Firewall (Just in case)
  community.windows.win_firewall_rule:
    name: "Remote Desktop"
    localport: 3389
    action: allow
    direction: in
    protocol: tcp
    profiles: 